USE SQLTEXT
GO
--TAO TRIGGER KHI CO BAI VIET MOI THI THONG BAO
CREATE TRIGGER ASM1_TRIGER1
ON dbo.POST_PROFILE
FOR INSERT, UPDATE
AS
BEGIN
    PRINT 'CO BAI VIET MOI '
END


-- TAO SP DE SELECT THONG TIN TREN BANG POST_PROFILE
CREATE PROCEDURE SelectAllPOST
AS
SELECT * FROM POST_PROFILE
GO;

-- TAO Function TRA VE TEN CAC BAI VIET
CREATE FUNCTION UF_TENBAIVIET()
RETURNS TABLE
AS RETURN SELECT TENBV FROM POST_PROFILE
GO

-- TAO INDEX
CREATE INDEX indexname ON POST_PROFILE(POSTID)

-- TAO TRANSACTION
BEGIN TRANSACTION
INSERT INTO POST_PROFILE
VALUES (120,'equality','Under the Prime Minister’s decision on the gender equality communication programme issued on October 23, 2021, 95 per cent of village codes','2021-01-15','NGUYEN VAN E','NGUYEN VAN F','CHINH TRI',NULL,5)
SELECT * FROM POST_PROFILE
COMMIT TRANSACTION 

--Truy vấn dữ liệu trên một bảng
SELECT * 
FROM USER_PROFILE

--Truy vấn có sử dụng Order by
SELECT *
FROM USER_PROFILE
ORDER BY USERID DESC

--Truy vấn sử dụng toán tử Like và các so sánh xâu ký tự
SELECT * FROM USER_PROFILE
WHERE USERADRESS LIKE 'Q%';

--Truy vấn liên quan tới điều kiện về thời gian
SELECT * FROM USER_PROFILE
WHERE BIRTH_DATE = '1990-01-04'

--Truy vấn dữ liệu từ nhiều bảng sử dụng Inner join
SELECT TENBV,TEN_THE_LOAI
FROM POST_PROFILE
JOIN THE_LOAI
ON POST_PROFILE.POSTID = THE_LOAI.POSTID

--Truy vấn sử dụng Outer join.truy vấn thông tin BÀI VIẾT,TÊN THỂ LOẠI,NGÀY ĐĂNG,TÊN PV CỦA NHỮNG BÀI POST CÓ ID < 115
SELECT TENBV,TEN_THE_LOAI,NGAYDANG,TENPV
FROM POST_PROFILE
FULL OUTER JOIN THE_LOAI
ON POST_PROFILE.POSTID = THE_LOAI.POSTID
WHERE POST_PROFILE.POSTID < 115;

--Truy vấn sử dụng truy vấn con,truy vấn thông tin của người viết chủ đề LAM DEP
SELECT *
FROM POST_PROFILE
WHERE POSTID = (SELECT POSTID FROM THE_LOAI WHERE TEN_THE_LOAI = 'LAM DEP')

--Truy vấn sử dụng With.TÌM THÔNG TIN CỦA NGƯỜI VIẾT BÀI VIẾT CÓ POSTID = 110
WITH aaa(bbb) as (SELECT TENPV FROM POST_PROFILE  WHERE POSTID = 110)
SELECT USERNAME,USERPASSWORD,BIRTH_DATE,PHONE
FROM USER_PROFILE,aaa
WHERE USER_PROFILE.USERNAME = aaa.bbb;

--Truy vấn thống kê sử dụng Group by và Having,truy vấn tên và số lượng bài viết của phóng viên
USE SQLTEXT
SELECT TENPV ,COUNT(*)
FROM POST_PROFILE
GROUP BY TENPV
HAVING TENPV LIKE 'N%'

--Truy vấn sử dụng function (hàm) đã viết trong bước trước.
SELECT * FROM UF_TENBAIVIET()

